name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: sbt
        
    - uses: sbt/setup-sbt@v1
      with:
        sbt-runner-version: 1.11.2
        
    - name: Build and test
      shell: bash
      run: sbt ci